# HydroSim install script for the sim PC (Windows).
# Run once from the repo root:   powershell -ExecutionPolicy Bypass -File windows\install.ps1
#
# It creates the Python venv, installs dependencies, generates .env with fresh
# secrets, and writes collector\collector.ini with the matching API token.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

Write-Host "== HydroSim install ==" -ForegroundColor Cyan

# --- Python ------------------------------------------------------------------
$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) {
    Write-Error "Python not found. Install Python 3.12+ from https://www.python.org/downloads/ (tick 'Add python.exe to PATH') and re-run."
}
$version = & python -c "import sys; print('{}.{}'.format(*sys.version_info[:2]))"
Write-Host "Python $version found."

# --- venv + dependencies -----------------------------------------------------
if (-not (Test-Path ".venv")) {
    Write-Host "Creating virtual environment…"
    python -m venv .venv
}
& .venv\Scripts\python -m pip install --upgrade pip --quiet
& .venv\Scripts\pip install -r requirements.txt --quiet
Write-Host "Dependencies installed."

# --- helpers -----------------------------------------------------------------
function New-Secret { -join ((48..57) + (97..122) | Get-Random -Count 40 | ForEach-Object { [char]$_ }) }

# --- .env --------------------------------------------------------------------
if (-not (Test-Path ".env")) {
    $secret = New-Secret
    $token  = New-Secret
    $admin  = New-Secret
    @"
# HydroSim — sim PC configuration (generated by install.ps1)
SECRET_KEY=$secret
API_TOKEN=$token
ADMIN_PASSWORD=$admin
FLASK_DEBUG=0

# Local server: the kiosk browser runs on this same PC.
HOST=127.0.0.1
PORT=8088
KIOSK_OPEN=1

# Live view on the internet — fill in UPSTREAM_TOKEN with the API_TOKEN that is
# configured on the Coolify app (see DEPLOY.md), then restart start.bat.
UPSTREAM_URL=https://sim.hydroteam.be
UPSTREAM_TOKEN=
"@ | Set-Content -Encoding UTF8 .env
    Write-Host ".env created. Admin password: $admin  (also in .env)" -ForegroundColor Yellow
} else {
    Write-Host ".env already exists - leaving it untouched."
}

# --- collector.ini -----------------------------------------------------------
if (-not (Test-Path "collector\collector.ini")) {
    $envMap = @{}
    Get-Content .env | Where-Object { $_ -match "^\s*([A-Z_]+)=(.*)$" } |
        ForEach-Object { $envMap[$Matches[1]] = $Matches[2] }
    (Get-Content "collector\collector.example.ini") `
        -replace "token = CHANGE-ME", "token = $($envMap['API_TOKEN'])" `
        -replace "8088", $envMap['PORT'] |
        Set-Content -Encoding UTF8 "collector\collector.ini"
    Write-Host "collector\collector.ini created with the matching token."
} else {
    Write-Host "collector\collector.ini already exists - leaving it untouched."
}

Write-Host ""
Write-Host "Done. Next steps:" -ForegroundColor Cyan
Write-Host "  1. windows\start.bat        starts server + collector + kiosk screen"
Write-Host "  2. Open http://127.0.0.1:8088/admin and create/activate an event"
Write-Host "     (admin password: see ADMIN_PASSWORD in .env)"
Write-Host "  3. For the public live view, set UPSTREAM_TOKEN in .env (DEPLOY.md)"
